# Generated by Django 4.2.16 on 2025-01-19 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModeloAdmin',
        ),
    ]
