# Generated by Django 4.2.16 on 2025-01-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0002_delete_modeloadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='tipo',
            field=models.CharField(choices=[('trl', 'TRL'), ('crl', 'CRL')], default='TRL', max_length=30),
        ),
    ]
