# Generated by Django 4.2.18 on 2025-01-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0004_rename_model_pregunta_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
